"""
Données de seed pour les bâtiments (référentiel statique).
"""

from backend.app.utils.constants import BuildingCategory

# Liste des bâtiments disponibles
BUILDINGS_DATA = [
    # BASE
    {
        "key": "warehouse",
        "name": "Entrepôt",
        "description": "Stocke les ressources du village. Augmente la capacité de stockage.",
        "category": BuildingCategory.BASE.value,
        "build_cost": {"wood": 50, "stone": 30},
        "production": None,
        "bonuses": {"warehouse_capacity_bonus": 500},
        "automation_type": None,
        "requirements": None,
        "max_instances": 5,
        "unlock_level": 1,
    },
    {
        "key": "inn",
        "name": "Auberge",
        "description": "Lieu de repos et de rencontre. Augmente le moral des villageois.",
        "category": BuildingCategory.BASE.value,
        "build_cost": {"wood": 80, "stone": 40, "cloth": 20},
        "production": None,
        "bonuses": {"moral_bonus": 10},
        "automation_type": None,
        "requirements": None,
        "max_instances": 3,
        "unlock_level": 1,
    },
    {
        "key": "library",
        "name": "Bibliothèque",
        "description": "Centre de connaissance. Accélère les recherches technologiques.",
        "category": BuildingCategory.BASE.value,
        "build_cost": {"wood": 100, "stone": 60, "paper": 50, "ink": 10},
        "production": {"resource": "knowledge_points", "amount_per_hour": 5, "storage_capacity": 100},
        "bonuses": {"research_speed_bonus_percent": 20},
        "automation_type": None,
        "requirements": None,
        "max_instances": 2,
        "unlock_level": 3,
    },
    
    # PRODUCTION
    {
        "key": "well",
        "name": "Puits",
        "description": "Produit de l'eau potable pour le village.",
        "category": BuildingCategory.PRODUCTION.value,
        "build_cost": {"wood": 30, "stone": 50},
        "production": {"resource": "water", "amount_per_hour": 20, "storage_capacity": 200},
        "bonuses": None,
        "automation_type": None,
        "requirements": None,
        "max_instances": 10,
        "unlock_level": 1,
    },
    {
        "key": "lumbermill",
        "name": "Scierie",
        "description": "Transforme les arbres en bois utilisable.",
        "category": BuildingCategory.PRODUCTION.value,
        "build_cost": {"wood": 60, "stone": 40, "metal": 20},
        "production": {"resource": "wood", "amount_per_hour": 15, "storage_capacity": 300},
        "bonuses": None,
        "automation_type": None,
        "requirements": None,
        "max_instances": 5,
        "unlock_level": 1,
    },
    {
        "key": "quarry",
        "name": "Carrière",
        "description": "Extrait la pierre des montagnes.",
        "category": BuildingCategory.PRODUCTION.value,
        "build_cost": {"wood": 40, "metal": 30},
        "production": {"resource": "stone", "amount_per_hour": 10, "storage_capacity": 250},
        "bonuses": None,
        "automation_type": None,
        "requirements": None,
        "max_instances": 5,
        "unlock_level": 1,
    },
    {
        "key": "mine",
        "name": "Mine",
        "description": "Extrait le métal et les minerais rares.",
        "category": BuildingCategory.PRODUCTION.value,
        "build_cost": {"wood": 80, "stone": 100},
        "production": {"resource": "metal", "amount_per_hour": 8, "storage_capacity": 150},
        "bonuses": None,
        "automation_type": None,
        "requirements": None,
        "max_instances": 3,
        "unlock_level": 2,
    },
    {
        "key": "farm",
        "name": "Ferme",
        "description": "Cultive du blé et produit de la nourriture.",
        "category": BuildingCategory.PRODUCTION.value,
        "build_cost": {"wood": 70, "stone": 30, "seeds": 20},
        "production": {"resource": "wheat", "amount_per_hour": 12, "storage_capacity": 200},
        "bonuses": None,
        "automation_type": None,
        "requirements": None,
        "max_instances": 10,
        "unlock_level": 1,
    },
    {
        "key": "hunting_lodge",
        "name": "Pavillon de chasse",
        "description": "Permet de chasser pour obtenir de la viande et du cuir.",
        "category": BuildingCategory.PRODUCTION.value,
        "build_cost": {"wood": 60, "stone": 20},
        "production": {"resource": "meat", "amount_per_hour": 8, "storage_capacity": 150},
        "bonuses": None,
        "automation_type": None,
        "requirements": None,
        "max_instances": 5,
        "unlock_level": 1,
    },
    {
        "key": "textile_workshop",
        "name": "Atelier textile",
        "description": "Produit du tissu et du lin.",
        "category": BuildingCategory.PRODUCTION.value,
        "build_cost": {"wood": 50, "stone": 30, "cotton": 30},
        "production": {"resource": "cloth", "amount_per_hour": 6, "storage_capacity": 100},
        "bonuses": None,
        "automation_type": None,
        "requirements": {"researches": ["textile_production"]},
        "max_instances": 3,
        "unlock_level": 2,
    },
    {
        "key": "herbalist",
        "name": "Herboriste",
        "description": "Cultive et prépare des plantes médicinales.",
        "category": BuildingCategory.PRODUCTION.value,
        "build_cost": {"wood": 40, "stone": 20, "seeds": 10},
        "production": {"resource": "herb", "amount_per_hour": 5, "storage_capacity": 80},
        "bonuses": None,
        "automation_type": None,
        "requirements": None,
        "max_instances": 3,
        "unlock_level": 2,
    },
    
    # MILITARY
    {
        "key": "barracks",
        "name": "Caserne",
        "description": "Entraîne les personnages au combat. Bonus XP pour les missions.",
        "category": BuildingCategory.MILITARY.value,
        "build_cost": {"wood": 100, "stone": 80, "metal": 40},
        "production": None,
        "bonuses": {"xp_bonus_percent": 15},
        "automation_type": None,
        "requirements": None,
        "max_instances": 2,
        "unlock_level": 2,
    },
    {
        "key": "armory",
        "name": "Armurerie",
        "description": "Forge des équipements de qualité supérieure.",
        "category": BuildingCategory.MILITARY.value,
        "build_cost": {"wood": 60, "stone": 40, "metal": 60},
        "production": None,
        "bonuses": {"equipment_craft_bonus_percent": 10},
        "automation_type": None,
        "requirements": {"researches": ["metalworking"]},
        "max_instances": 2,
        "unlock_level": 3,
    },
    {
        "key": "watchtower",
        "name": "Tour de guet",
        "description": "Surveille les environs et prévient les dangers.",
        "category": BuildingCategory.MILITARY.value,
        "build_cost": {"wood": 80, "stone": 100},
        "production": None,
        "bonuses": {"mission_success_bonus_percent": 5},
        "automation_type": None,
        "requirements": None,
        "max_instances": 5,
        "unlock_level": 2,
    },
    
    # WELLBEING
    {
        "key": "infirmary",
        "name": "Infirmerie",
        "description": "Soigne les blessés et augmente la récupération de HP.",
        "category": BuildingCategory.WELLBEING.value,
        "build_cost": {"wood": 70, "stone": 50, "herb": 30},
        "production": None,
        "bonuses": {"hp_regen_bonus_percent": 50, "moral_bonus": 5},
        "automation_type": None,
        "requirements": None,
        "max_instances": 2,
        "unlock_level": 2,
    },
    {
        "key": "garden",
        "name": "Jardin",
        "description": "Espace vert relaxant qui améliore le moral.",
        "category": BuildingCategory.WELLBEING.value,
        "build_cost": {"wood": 40, "seeds": 20, "water": 50},
        "production": None,
        "bonuses": {"moral_bonus": 8},
        "automation_type": None,
        "requirements": None,
        "max_instances": 10,
        "unlock_level": 1,
    },
    {
        "key": "training_ground",
        "name": "Terrain d'entraînement",
        "description": "Permet aux personnages de s'entraîner et gagner de l'XP.",
        "category": BuildingCategory.WELLBEING.value,
        "build_cost": {"wood": 90, "stone": 60},
        "production": None,
        "bonuses": {"xp_bonus_percent": 10},
        "automation_type": None,
        "requirements": None,
        "max_instances": 3,
        "unlock_level": 2,
    },
    
    # AUTOMATION
    {
        "key": "auto_harvester",
        "name": "Récolteur automatique",
        "description": "Automatise la récolte de ressources de base (nécessite worker).",
        "category": BuildingCategory.AUTOMATION.value,
        "build_cost": {"wood": 150, "stone": 100, "metal": 80, "mechanical_parts": 20},
        "production": None,
        "bonuses": None,
        "automation_type": "auto_harvest",
        "requirements": {"researches": ["automation_level_1"]},
        "max_instances": 5,
        "unlock_level": 5,
    },
    {
        "key": "auto_crafter",
        "name": "Établi automatique",
        "description": "Automatise le craft d'objets simples (nécessite worker).",
        "category": BuildingCategory.AUTOMATION.value,
        "build_cost": {"wood": 120, "stone": 80, "metal": 100, "mechanical_parts": 30},
        "production": None,
        "bonuses": None,
        "automation_type": "auto_craft",
        "requirements": {"researches": ["automation_level_2"]},
        "max_instances": 3,
        "unlock_level": 6,
    },
    {
        "key": "research_lab",
        "name": "Laboratoire de recherche",
        "description": "Automatise la progression des recherches (nécessite worker).",
        "category": BuildingCategory.AUTOMATION.value,
        "build_cost": {"wood": 100, "stone": 120, "metal": 60, "book": 50, "electronic_component": 10},
        "production": None,
        "bonuses": {"research_speed_bonus_percent": 30},
        "automation_type": "auto_research",
        "requirements": {"researches": ["automation_level_3"]},
        "max_instances": 2,
        "unlock_level": 7,
    },
]
